imp API Triggered Notifications
topcoder-platform/taas-apis pull request #482
Opened 2021-08-12 14:55 UTC by xxcxy

Slack notifications screenshots:
[Job Candidate is Selected] https://monosnap.com/file/cd8JqhNb5NthQzVxN3aX38CFa1NQic 
[Overlapping Interview Invites] https://monosnap.com/file/Dm74Kzf50AW40OZOZTU19f79Hj89jl

ps: if you have a slack `webhooks` url, you can set `slackURL` in `scripts/demo-email-notifications/index.js`.

2021-08-13 09:51 UTC, maxceem requested changes
Thanks @xxcxy, it works great. Just would like make some code and format improvements.

Please, check comments below for code improvements.

And here are some email/slack format improvements, basicaly:
- update title
- make all the team and job names as links
- remove separate links to keep space
- format dates in EDT timezone using the next date format: `Jan 17, 2020, 7:12 am EDT`

1. New Job Created (email)

    ![image](https://user-images.githubusercontent.com/146016/129336662-b4bfc043-166b-4274-98cc-a255a4c6c207.png)

2. New Team Created (email)

    ![image](https://user-images.githubusercontent.com/146016/129337475-f6097559-bb5d-4c7f-bfdb-00c6c3571058.png)

3. Overlapping Interview Invites (email)

    ![image](https://user-images.githubusercontent.com/146016/129338065-60127a59-d017-4b16-83bc-967106c429f1.png)
    
4. Job Candidate is Selected (email)
    
    ![image](https://user-images.githubusercontent.com/146016/129338741-0f0705f7-45d8-42f3-9c28-cd4e730622fd.png)

5. Resource Booking is Placed (email)

    ![image](https://user-images.githubusercontent.com/146016/129338169-07da6e9b-0c68-4ed9-add3-cb608dbb745a.png)

Similar for Slack:
- make team name and job title as links
- remove separate links
- format dates in EDT timezone using the next date format: `Jan 17, 2020, 7:12 am EDT`

![image](https://user-images.githubusercontent.com/146016/129339232-bfd78815-b63d-473d-9179-cc9fb2eaf191.png)

2021-08-13 09:51 UTC, maxceem commented on scripts/demo-email-notifications/index.js
> +const slackURL = null
Can we please, config `slackURL` using ENV variable for this script, and update README of this script accordingly.

2021-08-13 09:51 UTC, maxceem commented on src/eventHandlers/InterviewEventHandler.js
> +  })
We should **not** take into account interviews in status `Completed` or `Cancelled` for both `interview` and `overlappingInterview`.

2021-08-13 09:51 UTC, maxceem commented on src/eventHandlers/ResourceBookingEventHandler.js
> +  })
Let's put this code into a separate function.
We create separate functions for each separate logic. For example method `placeJobCandidate` is to change status of JobCandidate when RB is placed.

2021-08-13 09:51 UTC, maxceem commented on src/eventHandlers/JobEventHandler.js
> +async function processCreate (payload) {
Can we please, create a separate function to send notifications and call it inside `processCreate` like we do in other places. This way we separate functionality for each kind of logic.

2021-08-13 12:42 UTC, xxcxy commented on src/common/helper.js
> +  }
emmm...  if use the user token, creating team will fail from postman. Will revert this.

2021-08-13 13:03 UTC, maxceem commented on src/common/helper.js
> +  }
got it, but we have to revert it.

to test it from postman locally, you would have to use real token from DEV environment and make the next change to bypass token validation:
```
In tc-project-service/node_modules/tc-core-library-js/lib/auth/verifier.js add this to line 23:

callback(undefined, decodedToken.payload);
return;
```

2021-08-14 08:53 UTC, maxceem approved these changes
Thank you @xxcxy. Works good as per local testing.

2021-08-14 08:53 UTC, merged