fix: issue #475
topcoder-platform/taas-apis pull request #483
Opened 2021-08-13 00:12 UTC by yoution

@maxceem please review

2021-08-13 11:20 UTC, maxceem requested changes
Thank you @yoution. It works good, I only would like to make some updates for the code.

1. The way it is implemented now, the resume would be downloaded by the TaaS API and then sent to the client by the TaaS API. Can we avoid downloading resume TaaS API, and just redirect to the resume like this https://expressjs.com/en/api.html#res.redirect ?

2. Let's add a title to the email:

    ![image](https://user-images.githubusercontent.com/146016/129349671-e97de1ce-9d39-4c16-a46c-c0d6c74f00d4.png)

Also, please check comments to the code below.

2021-08-13 11:20 UTC, maxceem commented on app-constants.js
> +const TopCoderUserPermissionRole = UserRoles.TopcoderUser
I guess there is no need to export this role separately, can use it as `UserRoles.TopcoderUser` inside the code

2021-08-13 11:20 UTC, maxceem commented on src/services/JobCandidateService.js
> +  }
Let's wrap it in `try / catch` and if some error happened during email notification sending we just log error, but still error resume downloading.

2021-08-13 11:49 UTC, yoution commented
@maxceem 
`Let's add a title to the email:`, the html is using `table` layout, it is a little complex, is there any web tools to automatically create the layout?

2021-08-13 11:52 UTC, maxceem commented
@yoution we already support title, just pass `description: "Client Viewed Resume"` inside the email data and it would be inserted inside email here https://github.com/topcoder-platform/taas-apis/blob/feature/notifications-api/data/notifications-email-template.html#L75.

2021-08-14 11:23 UTC, maxceem approved these changes
thank you @yoution works good as per local testing.

2021-08-14 11:23 UTC, merged