implement local event handling
topcoder-platform/taas-apis pull request #79
Opened 2020-12-22 08:23 UTC by imcaizheng

## Notes
- The event handling is implemented in an asynchronous way so that it conforms to the original requirement mentioned on https://github.com/topcoder-platform/taas-apis/issues/54, and, the logic is still decoupled in the meantime.
- The logic at `src/app-routes.js` and inside function `ResourceBookingService.updateResourceBooking` are slightly altered
    to work with the event handling. Please review these changes particularly to ensure nothing would be broken due to that.

2020-12-25 12:40 UTC, maxceem requested changes
@imcaizheng, automatic updates doesn't work for me. When I make any action which supposes to trigger automatic updates, I get error.

1. When I update ResourceBooking status to `assigned` I get an error:

    ![image](https://user-images.githubusercontent.com/146016/103135057-6197c900-46be-11eb-8faa-2435309c0610.png)

    - To reproduce I create Job, JobCandidate and ResourceBooking using the same userId, to trigger automatic status update logic.

2. If I change the status of Job to `cancelled` I get an error:

     ![image](https://user-images.githubusercontent.com/146016/103135113-b9363480-46be-11eb-9429-fdc4c36460ef.png)

2020-12-26 08:30 UTC, imcaizheng commented on app-routes.js
> +              req.authUser = helper.authUserAsM2M()
@maxceem PR updated as per your suggestions.

2020-12-26 08:41 UTC, imcaizheng commented
@maxceem I tried to resolve the conflict between the PR and dev branch but I did it wrongly. Please discard the last commit and merge the last but one, named `revert the change made to app-routes.js`.

2020-12-26 10:23 UTC, maxceem commented
@imcaizheng hmm, I don't think there is a way to discard the last commit during merging. Could you please, revert the wrong commit from `imcaizheng:implement-event-handlers` branch, so it's not included in the PR?

2020-12-26 11:00 UTC, imcaizheng commented
@maxceem Thanks. The change is reverted.

2020-12-28 15:12 UTC, maxceem requested changes
> @maxceem Thanks. The change is reverted.

@imcaizheng Looks like during merging changes that were done for permissions in this PR https://github.com/topcoder-platform/taas-apis/pull/77 were reverted.

![image](https://user-images.githubusercontent.com/146016/103223706-77f88b80-492f-11eb-8e96-ad9231bbc717.png)

I try to test functionality anyway:
- When I assign Resouce Booking the corresponding JobCandidate became 'selected'.
- But if I cancel Job, corresponding Resource Booking and JobCandidates are not cancelled.

2020-12-28 17:04 UTC, imcaizheng commented
@maxceem
Please accept this PR https://github.com/topcoder-platform/taas-es-processor/pull/5 for `taas-es-processor` and try again. Resource Booking and JobCandidates could be properly cancelled after that.

2020-12-28 17:52 UTC, closed without merging